title: Gabriela Araujo
author: Gabriela Araujo
email: gabriela.araujo@barcelonagse.eu
description: >- 
  Personal academic website of Gabriela Araujo

theme: minima

baseurl: "" # Keep blank for user.github.io root site
url: "https://araujo-gabriela.github.io"

# Navigation links
header_pages:
  - research.md
  - teaching.md
  - cv.md
